config:
  target: "http://127.0.0.1:3500"
  phases:
    - duration: 60
      arrivalRate: 20
      name: VU - 10
    - duration: 30
      arrivalRate: 20
      rampTo: 100
      name: VU - 50
    - duration: 30
      arrivalRate: 20
      rampTo: 300
      name: VU - 150
    - duration: 30
      arrivalRate: 25
      rampTo: 500
      name: VU - 500
    - duration: 120
      arrivalRate: 50
      rampTo: 500
      name: VU - 500
    - duration: 120
      arrivalRate: 100
      rampTo: 1000
      name: Sustain VU - 500
  payload:
    path: "product.csv"
    fields:
      - "productId"
  plugins:
    metrics-by-endpoint:
      # Group metrics by request name rather than URL:
      useOnlyRequestNames: true

scenarios:
  - name: "GET/products"
    flow:
      - get:
          url: "/products/{{ productId }}"
          name: "GET/products"
      - think: 1
      - get:
          url: "/products/{{ productId }}"
          name: "GET/products"
      - think: 1
      - get:
          url: "/products/{{ productId }}"
          name: "GET/products"
